# Generated by Django 4.2.14 on 2024-08-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_post_commentroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentRoom',
        ),
    ]
