# Generated by Django 4.2.14 on 2024-08-15 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_comment_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 15, 10, 48, 40, 363073, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
