# Generated by Django 4.2.14 on 2024-08-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_alter_comment_posted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
