# Generated by Django 4.2.14 on 2024-08-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile-images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'пользователя',
                'verbose_name_plural': 'пользователей',
                'db_table': 'user',
            },
        ),
    ]
