# Generated by Django 4.2 on 2024-08-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
