# Generated by Django 4.2.14 on 2024-08-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0002_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
