# Generated by Django 4.2.14 on 2024-08-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Лайки поста'),
        ),
    ]
