# Generated by Django 4.2.14 on 2024-08-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_delete_commentroom'),
        ('feed', '0003_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Лайки поста'),
        ),
    ]
