# Generated by Django 4.2.14 on 2024-08-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
