# Generated by Django 4.2.14 on 2024-08-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_date',
            field=models.DateField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
