# Generated by Django 4.2.14 on 2024-08-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_post_posted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
